// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACtQ0iiD35BcJ4pUp8WUektqHH7s5p0kM',
    appId: '1:158918004863:web:5ba481a0bd796d5e92af4a',
    messagingSenderId: '158918004863',
    projectId: 'athang-expense-tracker',
    authDomain: 'athang-expense-tracker.firebaseapp.com',
    storageBucket: 'athang-expense-tracker.appspot.com',
    measurementId: 'G-L3KWKD337F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxr1e40kPD9enXEg7QhVXadlsUk7tSL5E',
    appId: '1:158918004863:android:4bfe2fc25ed1677192af4a',
    messagingSenderId: '158918004863',
    projectId: 'athang-expense-tracker',
    storageBucket: 'athang-expense-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUcKQtKEjS0otlnG6X7lg6Mw_u2lbqgho',
    appId: '1:158918004863:ios:70734a0b7917fd6792af4a',
    messagingSenderId: '158918004863',
    projectId: 'athang-expense-tracker',
    storageBucket: 'athang-expense-tracker.appspot.com',
    iosBundleId: 'com.example.athangExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUcKQtKEjS0otlnG6X7lg6Mw_u2lbqgho',
    appId: '1:158918004863:ios:70734a0b7917fd6792af4a',
    messagingSenderId: '158918004863',
    projectId: 'athang-expense-tracker',
    storageBucket: 'athang-expense-tracker.appspot.com',
    iosBundleId: 'com.example.athangExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACtQ0iiD35BcJ4pUp8WUektqHH7s5p0kM',
    appId: '1:158918004863:web:49d06e36fe82356692af4a',
    messagingSenderId: '158918004863',
    projectId: 'athang-expense-tracker',
    authDomain: 'athang-expense-tracker.firebaseapp.com',
    storageBucket: 'athang-expense-tracker.appspot.com',
    measurementId: 'G-N6RW5EKYEZ',
  );
}
